export type PurchaseHistoryItem = {
  id: string;
  date: string;
  carName: string;
  statusLabel: string;
  statusTone: "danger" | "muted";
  title: string;
  amountYen: number;
  shopLabel: string;
  hasMemo: boolean;
  icon: "photo" | "gear" | "ring" | "car" | "monitor" | "link";
};

export const MOCK_PURCHASE_HISTORY: PurchaseHistoryItem[] = [
  {
    id: "p-001",
    date: "2022.12.13",
    carName: "WRX STI",
    statusLabel: "",
    statusTone: "muted",
    title: "商品名",
    amountYen: 1111,
    shopLabel: "Upgarage xx点",
    hasMemo: true,
    icon: "photo",
  },
  {
    id: "p-002",
    date: "2022.11.17",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "URL test",
    amountYen: 11,
    shopLabel: "",
    hasMemo: false,
    icon: "gear",
  },
  {
    id: "p-003",
    date: "2022.11.16",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "URL test",
    amountYen: 111,
    shopLabel: "",
    hasMemo: false,
    icon: "ring",
  },
  {
    id: "p-004",
    date: "2022.10.25",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "BRAITH BX-418 ｶーﾎﾞﾝｼｮーﾄｱﾝﾃﾅｼﾝｼｭｸ SI",
    amountYen: 2027,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "car",
  },
  {
    id: "p-005",
    date: "2022.10.25",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "ENDY EVI-011T 純正ﾅﾋﾞ 地ﾃﾞｼﾞ ﾁｭ-ﾅ-接続用 VIDEO IN ｹ-ﾌﾞﾙ ﾄﾖﾀ車用 7P",
    amountYen: 2027,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "monitor",
  },
  {
    id: "p-006",
    date: "2022.10.25",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "",
    amountYen: 10175,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "ring",
  },
  {
    id: "p-007",
    date: "2022.10.25",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "【特定のお客様のみ販売可能】ﾒ-ｶ-不明 ﾘｱﾋﾞﾗ-ﾊﾞ-",
    amountYen: 6101,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "link",
  },

  {
    id: "p-008",
    date: "2022.10.24",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 8",
    amountYen: 9800,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "ring",
  },
  {
    id: "p-009",
    date: "2022.10.23",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 9",
    amountYen: 2500,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "gear",
  },
  {
    id: "p-010",
    date: "2022.10.22",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 10",
    amountYen: 13138,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "ring",
  },
  {
    id: "p-011",
    date: "2022.10.21",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 11",
    amountYen: 777,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "link",
  },
  {
    id: "p-012",
    date: "2022.10.20",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 12",
    amountYen: 3300,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "monitor",
  },
  {
    id: "p-013",
    date: "2022.10.19",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 13",
    amountYen: 12000,
    shopLabel: "t千葉中央店",
    hasMemo: true,
    icon: "photo",
  },
  {
    id: "p-014",
    date: "2022.10.18",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 14",
    amountYen: 4980,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "car",
  },
  {
    id: "p-015",
    date: "2022.10.17",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 15",
    amountYen: 1580,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "gear",
  },
  {
    id: "p-016",
    date: "2022.10.16",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 16",
    amountYen: 8800,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "ring",
  },
  {
    id: "p-017",
    date: "2022.10.15",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 17",
    amountYen: 2100,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "link",
  },
  {
    id: "p-018",
    date: "2022.10.14",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 18",
    amountYen: 999,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "monitor",
  },
  {
    id: "p-019",
    date: "2022.10.13",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 19",
    amountYen: 6400,
    shopLabel: "t千葉中央店",
    hasMemo: false,
    icon: "car",
  },
  {
    id: "p-020",
    date: "2022.10.12",
    carName: "",
    statusLabel: "未設定",
    statusTone: "danger",
    title: "DUMMY ITEM 20",
    amountYen: 12345,
    shopLabel: "t千葉中央店",
    hasMemo: true,
    icon: "photo",
  },
];