import type { Metadata } from "next"; // ページの <title> や <meta> を型付きで定義するため
import { Geist, Geist_Mono } from "next/font/google"; // Google Fonts を Next公式の方法で読み込む
import "./globals.css";
import StyledComponentsRegistry from "./lib/styled-components-registry"; // styled-components をSSR対応で安全にするラッパー
import styled from "styled-components";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StyledComponentsRegistry>
          <App>
            <Body>
              <Sidebar>
                <SidebarTop>
                  <LogoMark aria-hidden="true">
                    <img src="/icons/icons8-u-red.png" alt="" />
                  </LogoMark>
                </SidebarTop>

                <SidebarChevron>
                    <img src="/icons/icons8-chevron-right.png" alt="" />
                </SidebarChevron>

                <SidebarNav>
                  <SidebarItem href="/user_search" data-active="true">
                    <SidebarItemText>
                      買取<br />査定
                    </SidebarItemText>
                  </SidebarItem>
                  <SidebarItem href="/">
                    <SidebarItemText>入庫</SidebarItemText>
                  </SidebarItem>
                  <SidebarItem href="/">
                    <SidebarItemText>
                      顧客<br />情報
                    </SidebarItemText>
                  </SidebarItem>
                </SidebarNav>
              </Sidebar>

              <Main>
                <Header>
                  <HeaderLeft>
                    <HeaderTitle>メンテナンスノート</HeaderTitle>
                  </HeaderLeft>
                  <HeaderRight>UPGARAGE練馬店</HeaderRight>
                </Header>

                <Content>{children}</Content>
              </Main>
            </Body>
          </App>

        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

/* ---------- styles ---------- */

const App = styled.div`
  height: 100vh;
  display: flex;
`;

const Body = styled.div`
  flex: 1;
  display: flex;
`;

const Sidebar = styled.aside`
  width: 72px;
  border-right: 1px solid #e5e7eb;
  display: flex;
  flex-direction: column;
`;

const SidebarTop = styled.div`
  height: 56px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #FFE000;
`;

const LogoMark = styled.div`
  width: 30px;
  background: #FFE000;
`;

const SidebarChevron = styled.div`
  height: 56px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-bottom: 1px solid #e5e7eb;
  img {
    width: 20px;
    height: 20px;
  }
`;

const SidebarNav = styled.nav`
`;

const SidebarItem = styled(Link)`
  display: flex;
  align-items: center;
  justify-content: center;
  height: 56px;

  border-bottom: 1px solid #e5e7eb;

  &:hover {
    background: #f3f4f6;
  }
`;

const SidebarItemText = styled.span`
  font-size: 12px;
`;

const Main = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
`;

const Header = styled.header`
  height: 56px;
  background:  #F7F7F7;
  display: flex;
  align-items: center;
  padding-left: 16px;
  padding-right: 16px;
`;

const HeaderLeft = styled.div`
`;

const HeaderTitle = styled.div`
  font-size: 14px;
  font-weight: 600;
`;

const HeaderRight = styled.div`
  margin-left: auto;
  font-size: 12px;
  color: #6b7280
`;

const Content = styled.main`
  flex: 1;
`;