import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./lib/styled-components-registry";
import styled from "styled-components";
import Link from "next/link";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StyledComponentsRegistry>
          <App>
            <Body>
              <Sidebar />
              <Main>
                <Header>
                  <HeaderLeft>
                    <HeaderTitle>メンテナンスノート</HeaderTitle>
                  </HeaderLeft>
                  <HeaderRight>UPGARAGE練馬店</HeaderRight>
                </Header>
                <Content>{children}</Content>
              </Main>
            </Body>
          </App>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

/* ---------- styles ---------- */

const App = styled.div`
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  display: flex;
`;

const Body = styled.div`
  flex: 1;
  display: flex;
  min-width: 0;
`;

const Main = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  min-width: 0;
  overflow-y: auto;
`;

const Header = styled.header`
  padding: 16px;
  background:  #F7F7F7;
  display: flex;
  align-items: center;
  padding-left: 16px;
  padding-right: 16px;
`;

const HeaderLeft = styled.div`
`;

const HeaderTitle = styled.div`
  font-size: 14px;
  font-weight: 600;
`;

const HeaderRight = styled.div`
  margin-left: auto;
  font-size: 12px;
`;

const Content = styled.main`
  flex: 1;
`;